# -*- coding: utf-8 -*-
"""requirements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vx2DwyDvMqhf_m1g1vum_elRJWYkxiJj
"""

streamlit
openai
pdfplumber
pandas
openpyxl